"""What survives a contract refresh.

The contract is regenerated by truncating the pyproject from its header and
writing a fresh block, so everything below it goes too. Five features had
their [tool.splent.config] deleted the moment they were released, taking
every declared default with them, and nothing said so: the release
succeeded, the tag was pushed, and the products quietly fell back to
whatever config.py happened to hardcode.
"""

import pytest

from splent_cli.commands.feature.feature_release import (
    _sections_not_owned_by_the_contract,
)


CONTRACT = """# ── Feature Contract (auto-generated) ────────────────────────────────────────
[tool.splent.contract]
description = "search feature"

[tool.splent.contract.provides]
routes = ["/search"]

[tool.splent.contract.requires]
features = []
"""


class TestWhatIsKept:
    def test_a_config_block_below_the_contract(self):
        tail = (
            CONTRACT
            + """
# ── Configuration ─────────────────────────────────────────────────────
[tool.splent.config]
SEARCH_PATH = "search"
SEARCH_LIMIT = 20
"""
        )

        kept = _sections_not_owned_by_the_contract(tail)

        assert "[tool.splent.config]" in kept
        assert 'SEARCH_PATH = "search"' in kept
        assert "SEARCH_LIMIT = 20" in kept

    def test_the_comment_written_above_it(self):
        """A comment above a table is about that table, and losing it turns
        a documented setting into a bare line."""
        tail = CONTRACT + '\n# Why this exists\n[tool.splent.config]\nA = "1"\n'

        assert "# Why this exists" in _sections_not_owned_by_the_contract(tail)

    def test_a_refinement_block(self):
        """The case that was already handled by hand, now covered by the
        same rule rather than by a second regex."""
        tail = CONTRACT + "\n[tool.splent.refinement]\noverrides = []\n"

        assert "[tool.splent.refinement]" in _sections_not_owned_by_the_contract(tail)

    def test_several_blocks_keep_their_order(self):
        tail = (
            CONTRACT
            + '\n[tool.splent.config]\nA = "1"\n\n[tool.splent.refinement]\nB = "2"\n'
        )

        kept = _sections_not_owned_by_the_contract(tail)

        assert kept.index("[tool.splent.config]") < kept.index(
            "[tool.splent.refinement]"
        )

    def test_a_table_that_is_not_splents_at_all(self):
        """A maintainer may have put anything down there."""
        tail = CONTRACT + "\n[tool.ruff]\nline-length = 88\n"

        assert "[tool.ruff]" in _sections_not_owned_by_the_contract(tail)


class TestWhatIsNot:
    def test_the_contract_itself(self):
        assert _sections_not_owned_by_the_contract(CONTRACT) == ""

    def test_its_subtables(self):
        kept = _sections_not_owned_by_the_contract(CONTRACT)

        assert "provides" not in kept
        assert "requires" not in kept

    def test_the_banner_above_the_contract(self):
        """It is regenerated with the block, so keeping it would duplicate
        it a little further down on every refresh."""
        kept = _sections_not_owned_by_the_contract(CONTRACT)

        assert "auto-generated" not in kept


class TestOddInput:
    @pytest.mark.parametrize("tail", ["", "\n", "# just a comment\n"])
    def test_nothing_to_keep_is_not_an_error(self, tail):
        assert _sections_not_owned_by_the_contract(tail) == ""
