"""
splent feature:inject-config

Generate or update a feature's config.py from env vars detected in source code.

Scans all .py files (except config.py itself) for os.getenv / os.environ calls,
extracts variable names and defaults, and generates a config.py with
inject_config(app) that injects them into app.config.
"""

import os
import re
from pathlib import Path

import click

from splent_cli.services import context
from splent_cli.utils.feature_utils import normalize_namespace


# regex patterns for os.getenv("KEY", "default") and os.environ.get("KEY", "default")
_GETENV_WITH_DEFAULT = re.compile(
    r"""os\.(?:getenv|environ\.get)\s*\(\s*['"]([A-Z][A-Z0-9_]+)['"]\s*,\s*(.+?)\s*\)""",
)
_GETENV_NO_DEFAULT = re.compile(
    r"""os\.(?:getenv|environ\.get)\s*\(\s*['"]([A-Z][A-Z0-9_]+)['"]\s*\)""",
)
_ENVIRON_BRACKET = re.compile(
    r"""os\.environ\s*\[\s*['"]([A-Z][A-Z0-9_]+)['"]\s*\]""",
)


def _scan_env_vars(src_dir: Path) -> list[tuple[str, str]]:
    """Scan source files for env var usage. Returns [(var_name, default_expr), ...]."""
    found: dict[str, str] = {}

    for py_file in sorted(src_dir.rglob("*.py")):
        if py_file.name == "config.py":
            continue
        if "migrations" in py_file.parts:
            continue

        text = py_file.read_text()

        for m in _GETENV_WITH_DEFAULT.finditer(text):
            var, default = m.group(1), m.group(2).strip().rstrip(")")
            if var not in found:
                found[var] = default

        for m in _GETENV_NO_DEFAULT.finditer(text):
            var = m.group(1)
            if var not in found:
                found[var] = '""'

        for m in _ENVIRON_BRACKET.finditer(text):
            var = m.group(1)
            if var not in found:
                found[var] = '""'

    return sorted(found.items())


def _infer_type_coercion(var: str, default: str) -> tuple[str, str]:
    """Return (config_value_expr, comment) for a var based on its default.

    Tries to detect int and bool patterns to add type coercion.
    """
    # Strip outer quotes if it's a string default
    stripped = default.strip("'\"")

    # Bool pattern: "True" / "False"
    if stripped.lower() in ("true", "false"):
        return (
            f'os.getenv("{var}", "{stripped}").lower() == "true"',
            "",
        )

    # Int pattern: pure digits or int() wrapper
    if re.fullmatch(r"\d+", stripped):
        return f'int(os.getenv("{var}", "{stripped}"))', ""

    # Already an int() call
    if default.startswith("int("):
        return f'int(os.getenv("{var}", "{stripped}"))', ""

    # Default string
    return f'os.getenv("{var}", {default})', ""


def _generate_config(env_vars: list[tuple[str, str]], feature_short: str) -> str:
    """Generate config.py content."""
    lines = [
        '"""',
        f"{feature_short} feature configuration.",
        "",
        "Auto-generated by `splent feature:inject-config`.",
        "Injects environment variables into Flask app.config.",
        '"""',
        "",
        "import os",
        "",
        "",
        "def inject_config(app):",
        "    app.config.update({",
    ]

    for var, default in env_vars:
        expr, _ = _infer_type_coercion(var, default)
        lines.append(f'        "{var}": {expr},')

    lines.append("    })")
    lines.append("")

    return "\n".join(lines)


def _read_existing_vars(config_path: Path) -> set[str]:
    """Read variable names from an existing config.py."""
    if not config_path.exists():
        return set()
    text = config_path.read_text()
    return set(re.findall(r'"([A-Z][A-Z0-9_]+)":\s*', text))


@click.command(
    "feature:inject-config",
    short_help="Generate or update config.py from env vars in source code.",
)
@click.argument("feature_ref")
@click.option("--dry-run", is_flag=True, help="Show what would be generated without writing.")
@context.requires_product
def feature_inject_config(feature_ref, dry_run):
    """Scan a feature's source code for os.getenv / os.environ calls and
    generate (or update) its config.py with inject_config(app).

    \b
    Examples:
      splent feature:inject-config splent_feature_confirmemail
      splent feature:inject-config splent_feature_auth --dry-run
    """
    workspace = str(context.workspace())

    # Resolve feature path
    if "/" in feature_ref:
        ns_raw, name = feature_ref.split("/", 1)
    else:
        ns_raw = "splent-io"
        name = feature_ref

    ns_safe = normalize_namespace(ns_raw)
    short = name.removeprefix("splent_feature_")

    # Find feature source dir
    feature_root = Path(workspace) / name
    if not feature_root.exists():
        click.secho(f"  Feature not found at workspace root: {feature_root}", fg="red")
        raise SystemExit(1)

    src_dir = feature_root / "src" / ns_safe / name
    if not src_dir.exists():
        click.secho(f"  Source dir not found: {src_dir}", fg="red")
        raise SystemExit(1)

    config_path = src_dir / "config.py"

    click.echo()
    click.secho(f"  feature:inject-config — {name}", bold=True)
    click.echo()

    # Scan
    env_vars = _scan_env_vars(src_dir)

    if not env_vars:
        click.secho("  No env vars found in source code.", fg="yellow")
        click.echo()
        return

    click.secho(f"  Detected {len(env_vars)} env var(s):", bold=True)
    for var, default in env_vars:
        click.echo(f"    {var:<35} default: {default}")
    click.echo()

    # Check existing
    existing = _read_existing_vars(config_path)
    new_vars = {v for v, _ in env_vars} - existing

    if config_path.exists() and not new_vars:
        click.secho("  ✅ config.py is already up to date.", fg="green")
        click.echo()
        return

    if config_path.exists() and new_vars:
        click.secho(f"  New vars to add: {', '.join(sorted(new_vars))}", fg="yellow")

    # Generate
    content = _generate_config(env_vars, short)

    if dry_run:
        click.secho("  Generated config.py (dry-run):", fg="cyan")
        click.echo()
        for line in content.splitlines():
            click.echo(f"    {line}")
        click.echo()
        return

    config_path.write_text(content)

    if existing:
        click.secho(f"  ✅ config.py updated ({len(new_vars)} new var(s)).", fg="green")
    else:
        click.secho("  ✅ config.py created.", fg="green")
    click.echo()


cli_command = feature_inject_config
