services:

  cli:
    container_name: splent_cli_container
    build:
      context: ../../
      dockerfile: splent_cli/docker/images/Dockerfile.cli
    volumes:
      - ../../:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.ssh:/home/splent/.ssh:ro
      - ${HOME}/.gitconfig:/home/splent/.gitconfig:rw
    stdin_open: true
    tty: true
    networks:
      - splent_network

networks:
  splent_network:
    name: splent_network
