"""
Shared release pipeline helpers used by product:release and feature:release.
"""

import os
import re
import sys
import subprocess
import requests
import click


def extract_repo(remote_url: str) -> str:
    """Extract 'org/repo' from a GitHub remote URL (HTTPS with/without token, or SSH)."""
    # HTTPS with token
    m = re.match(
        r"https://[^@]+@github\.com/(?P<org>[^/]+)/(?P<repo>.+?)\.git$", remote_url
    )
    if m:
        return f"{m.group('org')}/{m.group('repo')}"

    # HTTPS plain
    m = re.match(r"https://github\.com/(?P<org>[^/]+)/(?P<repo>.+?)\.git$", remote_url)
    if m:
        return f"{m.group('org')}/{m.group('repo')}"

    # SSH
    m = re.match(r"git@github\.com:(?P<org>[^/]+)/(?P<repo>.+?)\.git$", remote_url)
    if m:
        return f"{m.group('org')}/{m.group('repo')}"

    raise SystemExit(f"❌ Cannot extract GitHub repo from URL: {remote_url}")


def update_version(py_path: str, normalized: str):
    """Replace the version field in a pyproject.toml file."""
    with open(py_path, "r", encoding="utf-8") as f:
        content = f.read()

    new_content = re.sub(
        r'(?m)^version\s*=\s*["\'].*?["\']',
        f'version = "{normalized}"',
        content,
    )

    with open(py_path, "w", encoding="utf-8") as f:
        f.write(new_content)


def commit_local_changes(cwd: str, version: str, subject: str = "bump version"):
    r = subprocess.run(
        ["git", "status", "--porcelain"], capture_output=True, text=True, cwd=cwd
    )
    if not r.stdout.strip():
        click.echo("✅ Working tree clean.")
        return

    click.echo("⚠️ Local changes detected:")
    click.echo(r.stdout.strip())

    if not click.confirm("Commit and push?", default=True):
        raise SystemExit("🚫 Release cancelled.")

    try:
        subprocess.run(["git", "add", "-A"], cwd=cwd, check=True, capture_output=True)
        subprocess.run(
            ["git", "commit", "-m", f"chore: {subject} to {version}"],
            cwd=cwd, check=True, capture_output=True,
        )
        subprocess.run(
            ["git", "push", "origin", "main"],
            cwd=cwd, check=True, capture_output=True,
        )
    except subprocess.CalledProcessError as e:
        click.secho(f"❌ Git operation failed: {e.stderr.strip() if e.stderr else e}", fg="red")
        click.secho("   The version was bumped in pyproject.toml but not committed.", fg="yellow")
        click.secho("   Fix the git issue and re-run, or revert manually.", fg="yellow")
        raise SystemExit(1)

    click.echo("☁️ Changes committed and pushed.")


def create_and_push_git_tag(cwd: str, version: str):
    """Create an annotated tag and push it to origin."""
    try:
        subprocess.run(
            ["git", "fetch", "origin", "--tags"],
            cwd=cwd, check=True, capture_output=True,
        )
        tags = subprocess.run(
            ["git", "tag"],
            capture_output=True, text=True, cwd=cwd, check=True,
        ).stdout.splitlines()

        if version not in tags:
            subprocess.run(
                ["git", "tag", "-a", version, "-m", f"Release {version}"],
                cwd=cwd, check=True, capture_output=True,
            )
            click.echo(f"🏷️ Tag {version} created.")
        else:
            click.echo("⚠️ Tag already exists locally.")

        subprocess.run(
            ["git", "push", "origin", version],
            cwd=cwd, check=True, capture_output=True,
        )
        click.echo("☁️ Tag pushed.")
    except subprocess.CalledProcessError as e:
        stderr = e.stderr.strip() if e.stderr else e
        click.secho(
            f"❌ Git tag operation failed: {stderr}", fg="red"
        )
        click.secho(
            "   The commit was pushed but the tag may not be on remote.",
            fg="yellow",
        )
        raise SystemExit(1)


def create_github_release(repo: str, version: str, token: str | None):
    """Create a GitHub Release via API."""
    if not token:
        click.echo("⚠️ No GITHUB_TOKEN → skipping GitHub release.")
        return

    api_url = f"https://api.github.com/repos/{repo}/releases"
    version_number = version.lstrip("v")
    package = repo.split("/")[-1]

    body = (
        f"## 🎉 {version}\n\n"
        f"Automated release generated by **SPLENT**.\n\n"
        f"### 📦 Details\n"
        f"- **Tag:** `{version}`\n"
        f"- **Repository:** `{repo}`\n"
        f"- **Version:** `{version_number}`\n\n"
        f"### 📥 Installation (PyPI)\n"
        f"```\n"
        f"pip install {package}=={version_number}\n"
        f"```\n\n"
        f"### 🧩 Notes\n"
        f"This release was automatically tagged, packaged and published by the **SPLENT pipeline**.\n\n"
        f"---\n"
    )

    payload = {
        "tag_name": version,
        "name": f"Release {version}",
        "body": body,
        "draft": False,
        "prerelease": False,
    }

    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github+json",
    }

    resp = requests.post(api_url, headers=headers, json=payload)

    if resp.status_code in (200, 201):
        click.echo(f"✅ GitHub release created: {resp.json().get('html_url')}")
        return

    if resp.status_code == 422 and "already_exists" in resp.text:
        click.echo("⚠️ Release already exists. Skipping.")
        return

    click.echo(f"⚠️ Release failed: {resp.status_code} {resp.text}")


def build_and_upload_pypi(path: str):
    """Build the package and upload it to PyPI."""
    click.echo("📦 Building package...")
    subprocess.run(["rm", "-rf", "dist"], cwd=path)
    try:
        subprocess.run(
            [sys.executable, "-m", "build"], check=True, cwd=path
        )
    except subprocess.CalledProcessError:
        click.secho(
            "❌ Package build failed. Check the output above.", fg="red"
        )
        raise SystemExit(1)

    click.echo("📤 Uploading to PyPI...")
    try:
        subprocess.run(
            [sys.executable, "-m", "twine", "upload", "dist/*"],
            env=os.environ.copy(),
            check=True,
            cwd=path,
        )
    except subprocess.CalledProcessError:
        click.secho(
            "❌ PyPI upload failed. Check credentials and network.",
            fg="red",
        )
        click.secho(
            "   The package was built but not uploaded."
            " Run manually: twine upload dist/*",
            fg="yellow",
        )
        raise SystemExit(1)

    click.echo("✅ PyPI upload complete.")
