import os
import re
import sys
import subprocess
import requests
import click


# =====================================================================
# VALIDACIONES
# =====================================================================
def validate_product_release_env():
    missing = []

    if not os.getenv("GITHUB_TOKEN"):
        click.echo("⚠️ Warning: GITHUB_TOKEN not set → GitHub release will be skipped.")

    pypi_user = os.getenv("TWINE_USERNAME") or os.getenv("PYPI_USERNAME")
    pypi_pass = os.getenv("TWINE_PASSWORD") or os.getenv("PYPI_PASSWORD")

    if not pypi_user:
        missing.append("TWINE_USERNAME or PYPI_USERNAME")
    if not pypi_pass:
        missing.append("TWINE_PASSWORD or PYPI_PASSWORD")

    if not os.getenv("DOCKERHUB_USERNAME"):
        missing.append("DOCKERHUB_USERNAME")
    if not os.getenv("DOCKERHUB_PASSWORD"):
        missing.append("DOCKERHUB_PASSWORD")

    if missing:
        click.echo("❌ Missing required environment variables:")
        for m in missing:
            click.echo(f"   - {m}")
        raise SystemExit(1)


# =====================================================================
# EXTRACT REPO NAME
# =====================================================================
def extract_repo(remote_url: str) -> str:
    m = re.match(r"https://.*github\.com/(?P<org>[^/]+)/(?P<repo>.+?)\.git$", remote_url)
    if m:
        return f"{m.group('org')}/{m.group('repo')}"

    m = re.match(r"git@github\.com:(?P<org>[^/]+)/(?P<repo>.+?)\.git$", remote_url)
    if m:
        return f"{m.group('org')}/{m.group('repo')}"

    raise SystemExit(f"❌ Cannot extract GitHub repo from URL: {remote_url}")


# =====================================================================
# UPDATE VERSION IN pyproject.toml
# =====================================================================
def update_version(py_path, normalized):
    with open(py_path, "r", encoding="utf-8") as f:
        content = f.read()

    new_content = re.sub(
        r'(?m)^version\s*=\s*["\'].*?["\']',
        f'version = "{normalized}"',
        content,
    )

    with open(py_path, "w", encoding="utf-8") as f:
        f.write(new_content)


# =====================================================================
# COMMIT LOCAL CHANGES
# =====================================================================
def commit_local_changes(version):
    r = subprocess.run(["git", "status", "--porcelain"], capture_output=True, text=True)

    if not r.stdout.strip():
        click.echo("✅ Working tree clean.")
        return

    click.echo("⚠️ Local changes detected:")
    click.echo(r.stdout.strip())

    if not click.confirm("Commit and push?", default=True):
        raise SystemExit("🚫 Release cancelled.")

    subprocess.run(["git", "add", "-A"])
    subprocess.run(["git", "commit", "-m", f"chore: bump product version to {version}"])
    subprocess.run(["git", "push", "origin", "main"])

    click.echo("☁️ Changes committed and pushed.")


# =====================================================================
# TAG & PUSH
# =====================================================================
def create_and_push_git_tag(version):
    subprocess.run(["git", "fetch", "origin", "--tags"])
    tags = subprocess.run(["git", "tag"], capture_output=True, text=True).stdout.splitlines()

    if version not in tags:
        subprocess.run(["git", "tag", "-a", version, "-m", f"Release {version}"])
        click.echo(f"🏷️ Tag {version} created.")
    else:
        click.echo("⚠️ Tag already exists locally.")

    subprocess.run(["git", "push", "origin", version])
    click.echo("☁️ Tag pushed.")


# =====================================================================
# GITHUB RELEASE
# =====================================================================
def create_github_release(repo, version, token):
    if not token:
        click.echo("⚠️ No GITHUB_TOKEN → skipping GitHub release.")
        return

    api_url = f"https://api.github.com/repos/{repo}/releases"

    body = (
        f"## 🚀 Release {version}\n\n"
        f"Product release generated by **SPLENT**.\n\n"
        f"### 📦 Details\n"
        f"- **Tag:** `{version}`\n"
        f"- **Repository:** `{repo}`\n\n"
        f"### 🧩 Notes\n"
        f"This version was automatically packaged, tagged, and released by the SPLENT framework.\n"
    )

    payload = {
        "tag_name": version,
        "name": f"Release {version}",
        "body": body,
        "draft": False,
        "prerelease": False,
    }

    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github+json",
    }

    resp = requests.post(api_url, headers=headers, json=payload)

    if resp.status_code in (200, 201):
        click.echo(f"✅ GitHub release created: {resp.json().get('html_url')}")
    elif resp.status_code == 422 and "already_exists" in resp.text:
        click.echo("⚠️ Release already exists on GitHub.")
    else:
        click.echo(f"⚠️ GitHub release failed → {resp.status_code} {resp.text}")


# =====================================================================
# PYPI UPLOAD
# =====================================================================
def build_and_upload_pypi(product_path):
    os.chdir(product_path)

    click.echo("📦 Building package...")
    subprocess.run(["rm", "-rf", "dist"])
    subprocess.run([sys.executable, "-m", "build"], check=True)

    click.echo("📤 Uploading to PyPI...")
    env = os.environ.copy()
    subprocess.run(
        [sys.executable, "-m", "twine", "upload", "dist/*"],
        env=env,
        check=True
    )

    click.echo("✅ PyPI upload complete.")


# =====================================================================
# DOCKER RELEASE
# =====================================================================
def release_docker_image(product, version, docker_dir):
    username = os.getenv("DOCKERHUB_USERNAME")
    password = os.getenv("DOCKERHUB_PASSWORD")

    click.echo("🐳 Logging into Docker Hub...")
    subprocess.run(
        ["docker", "login", "-u", username, "-p", password],
        check=True
    )

    image_name = f"{username}/{product}"

    click.echo("🐳 Building Docker image...")
    subprocess.run(
        ["docker", "build", "-t", f"{image_name}:{version}", "-t", f"{image_name}:latest", docker_dir],
        check=True
    )

    click.echo("📤 Pushing Docker images...")
    subprocess.run(["docker", "push", f"{image_name}:{version}"], check=True)
    subprocess.run(["docker", "push", f"{image_name}:latest"], check=True)

    click.echo("✅ Docker Hub release complete.")


# =====================================================================
# COMMAND
# =====================================================================
@click.command(
    "product:release",
    short_help="Release a product: version bump, tag, GitHub release, PyPI release, DockerHub release.",
)
@click.argument("version")
@click.option("--product", default=None, help="Override SPLENT_APP.")
def product_release(version, product):
    validate_product_release_env()

    workspace = "/workspace"
    product = product or os.getenv("SPLENT_APP")

    if not product:
        click.echo("❌ No product specified and SPLENT_APP not set.")
        raise SystemExit(1)

    product_path = os.path.join(workspace, product)
    pyproject_path = os.path.join(product_path, "pyproject.toml")
    docker_dir = os.path.join(product_path, "docker")

    if not os.path.isfile(pyproject_path):
        click.echo(f"❌ pyproject.toml not found in product: {product}")
        raise SystemExit(1)

    click.echo(f"🚀 Releasing PRODUCT {product}@{version}")

    # Update version + commit local changes
    update_version(pyproject_path, version)
    commit_local_changes(version)

    # Tag + GitHub release
    create_and_push_git_tag(version)
    repo = extract_repo(
        subprocess.run(["git", "config", "--get", "remote.origin.url"], capture_output=True, text=True).stdout.strip()
    )

    create_github_release(repo, version, os.getenv("GITHUB_TOKEN"))

    # PyPI
    build_and_upload_pypi(product_path)

    # DockerHub release
    release_docker_image(product, version, docker_dir)

    click.echo("🎉 Product release completed!")
