import os
import re
import sys
import subprocess
import click
import requests


WORKSPACE = "/workspace"


# =====================================================================
# SHARED HELPERS (same philosophy as feature:release)
# =====================================================================

def validate_env():
    missing = []
    if not os.getenv("GITHUB_TOKEN"):
        click.echo("⚠️  GITHUB_TOKEN not set → GitHub release will be skipped.")
    if not (os.getenv("TWINE_USERNAME") or os.getenv("PYPI_USERNAME")):
        missing.append("TWINE_USERNAME or PYPI_USERNAME")
    if not (os.getenv("TWINE_PASSWORD") or os.getenv("PYPI_PASSWORD")):
        missing.append("TWINE_PASSWORD or PYPI_PASSWORD")
    if missing:
        click.echo("❌ Missing required environment variables:")
        for m in missing:
            click.echo(f"   - {m}")
        raise SystemExit(1)


def update_version(pyproject_path: str, version: str):
    with open(pyproject_path, "r", encoding="utf-8") as f:
        content = f.read()
    new_content = re.sub(
        r'(?m)^version\s*=\s*["\'].*?["\']',
        f'version = "{version}"',
        content,
    )
    with open(pyproject_path, "w", encoding="utf-8") as f:
        f.write(new_content)
    click.echo(f"✏️  Version bumped to {version} in pyproject.toml")


def commit_and_push(package_path: str, version: str):
    os.chdir(package_path)
    r = subprocess.run(["git", "status", "--porcelain"], capture_output=True, text=True)
    if not r.stdout.strip():
        click.echo("✅ Working tree clean — nothing to commit.")
        return
    click.echo("⚠️  Local changes detected:")
    click.echo(r.stdout.strip())
    if not click.confirm("Commit and push?", default=True):
        raise SystemExit("🚫 Release cancelled.")
    subprocess.run(["git", "add", "-A"], check=True)
    subprocess.run(["git", "commit", "-m", f"chore: bump version to {version}"], check=True)
    subprocess.run(["git", "push", "origin", "main"], check=True)
    click.echo("☁️  Changes committed and pushed.")


def tag_and_push(package_path: str, version: str) -> str:
    os.chdir(package_path)
    subprocess.run(["git", "fetch", "origin", "--tags"])
    tags = subprocess.run(["git", "tag"], capture_output=True, text=True).stdout.splitlines()
    tag = f"v{version}"
    if tag not in tags:
        subprocess.run(["git", "tag", "-a", tag, "-m", f"Release {tag}"], check=True)
        click.echo(f"🏷️  Tag {tag} created.")
    else:
        click.echo(f"⚠️  Tag {tag} already exists — skipping.")
    subprocess.run(["git", "push", "origin", tag], check=True)
    click.echo("☁️  Tag pushed.")
    return tag


def extract_repo(package_path: str) -> str:
    os.chdir(package_path)
    url = subprocess.run(
        ["git", "config", "--get", "remote.origin.url"],
        capture_output=True, text=True
    ).stdout.strip()
    for pattern in [
        r"https://[^@]+@github\.com/(?P<org>[^/]+)/(?P<repo>.+?)(?:\.git)?$",
        r"https://github\.com/(?P<org>[^/]+)/(?P<repo>.+?)(?:\.git)?$",
        r"git@github\.com:(?P<org>[^/]+)/(?P<repo>.+?)(?:\.git)?$",
    ]:
        m = re.match(pattern, url)
        if m:
            return f"{m.group('org')}/{m.group('repo')}"
    raise SystemExit(f"❌ Cannot extract GitHub repo from: {url}")


def create_github_release(repo: str, tag: str, version: str, token: str):
    if not token:
        click.echo("⚠️  No GITHUB_TOKEN → skipping GitHub release.")
        return
    package = repo.split("/")[-1]
    body = (
        f"## 🎉 {tag}\n\n"
        f"Automated release generated by **SPLENT**.\n\n"
        f"### 📦 Details\n"
        f"- **Tag:** `{tag}`\n"
        f"- **Repository:** `{repo}`\n"
        f"- **Version:** `{version}`\n\n"
        f"### 📥 Installation (PyPI)\n"
        f"```\n"
        f"pip install {package}=={version}\n"
        f"```\n\n"
        f"---\n"
        f"This release was automatically tagged, packaged and published by the **SPLENT pipeline**.\n"
    )
    resp = requests.post(
        f"https://api.github.com/repos/{repo}/releases",
        headers={
            "Authorization": f"token {token}",
            "Accept": "application/vnd.github+json",
        },
        json={"tag_name": tag, "name": f"Release {tag}", "body": body, "draft": False, "prerelease": False},
    )
    if resp.status_code in (200, 201):
        click.echo(f"✅ GitHub release created: {resp.json().get('html_url')}")
    elif resp.status_code == 422 and "already_exists" in resp.text:
        click.echo("⚠️  GitHub release already exists — skipping.")
    else:
        click.echo(f"⚠️  GitHub release failed: {resp.status_code} {resp.text}")


def build_and_upload(package_path: str):
    os.chdir(package_path)
    click.echo("📦 Building package...")
    subprocess.run(["rm", "-rf", "dist", "build"], check=True)
    subprocess.run(["find", ".", "-maxdepth", "1", "-name", "*.egg-info", "-exec", "rm", "-rf", "{}", "+"])
    subprocess.run(["find", ".", "-maxdepth", "1", "-type", "d", "-name", "*-*.*.*", "-exec", "rm", "-rf", "{}", "+"])
    subprocess.run([sys.executable, "-m", "build"], check=True)
    click.echo("📤 Uploading to PyPI...")
    subprocess.run(
        [sys.executable, "-m", "twine", "upload", "dist/*"],
        env=os.environ.copy(),
        check=True,
    )
    click.echo("✅ PyPI upload complete.")


def run_release(package_name: str, package_path: str, version: str):
    validate_env()

    normalized = version.lstrip("v")
    tag = f"v{normalized}"

    if not os.path.isdir(package_path):
        raise SystemExit(f"❌ Package directory not found: {package_path}")

    pyproject = os.path.join(package_path, "pyproject.toml")
    if not os.path.exists(pyproject):
        raise SystemExit(f"❌ pyproject.toml not found in {package_path}")

    click.echo(f"\n🚀 Releasing {package_name}@{normalized}\n")

    update_version(pyproject, normalized)
    commit_and_push(package_path, tag)
    tag_and_push(package_path, normalized)

    repo = extract_repo(package_path)
    create_github_release(repo, tag, normalized, os.getenv("GITHUB_TOKEN"))
    build_and_upload(package_path)

    click.echo(f"\n🎉 {package_name} {tag} released successfully!")


# =====================================================================
# COMMANDS
# =====================================================================

@click.command(
    "release:cli",
    short_help="Release splent_cli: bump version, tag, publish to GitHub/PyPI.",
)
@click.argument("version")
def release_cli(version: str):
    run_release("splent_cli", os.path.join(WORKSPACE, "splent_cli"), version)


@click.command(
    "release:framework",
    short_help="Release splent_framework: bump version, tag, publish to GitHub/PyPI.",
)
@click.argument("version")
def release_framework(version: str):
    run_release("splent_framework", os.path.join(WORKSPACE, "splent_framework"), version)
